baseURL = 'https://0xNOY.github.io/'
languageCode = 'en-us'
title = '0xPages'
theme = 'stack'

[params]
favicon = "/favicon.ico"

[params.footer]
since = 2023

[params.sidebar]
emoji = "🌮"
subtitle = "0xNOY's Blog & Notes"

[params.sidebar.avatar]
enabled = true
local = false
src = "https://github.com/0xNOY.png"

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"
